"""
Functions for performing code conversion are located
at this location.
"""


inline_function_template="""\
\t\"\"\"
This class was autogenerated due to a detection
of an inline function or class. It is a wrapper
which grabs required environmental information
at the moment of construction
\t\"\"\"
\tdef __init__(self, {environmental_args}):
\t{environmental_storage}
def __call__(self, {primary_args}):
\t{environmental_loading}
\t{original_code}
"""


