"""
A place to keep templates, and template constructors

"""
import inspect
import re
import datetime
from src import rcb

boilerplate_template="""\
\"\"\"
This is an automatically generated 
file produces by preprocessing. This
file is designed to be run within
the namespace it was called in.

Do not edit this file.

DEBUG_INFO:

This file was created from a file located at: {path}
This file was created at time: {time}

The environmental variables present 
upon creation are:

{environmentals}
\"\"\"
"""

torch_parse_error_template = """\
Error occurred in torchspace while handling {activity}


"""

def make_boilerplate_source(path: str, env: rcb.EnvProxy):
    """

    Makes the boilerplate commentary
    living at the front of each temporary
    file

    :path: The currently relevant file path
    :param env: The environment
    :return: A string of commentary
    """

    path = re.escape(path)
    time = datetime.datetime.now()
    vars = env.as_dict().keys()
    vars = [str(var) for var in vars]
    vars = "\n".join(vars)
    output = boilerplate_template.format(path=path,
                                        time=time,
                                        environmentals=vars)
    return output
